spring:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/scaffold?useUnicode=true&characterEncoding=UTF8&erverTimezone=Asia&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    second:
      url: jdbc:mysql://localhost:3306/scaffold2?useUnicode=true&characterEncoding=UTF8&erverTimezone=Asia&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: oahnus
    password: pass
    port: 5672
  redis:
    host: localhost
    port: 6379
    password: pass
