spring:
  profiles:
    active: dev
  application:
    name: scaffold

server:
  port: 8921

open:
  package: top.oahnus.controller.open
#  context-path: /hr

#swagger:
#  author: oahnus
#  url: www.oahnus.top
#  version: 0.0.1

