spring:
  profiles:
    active: dev
  application:
    name: scaffold


server:
  port: 8921
#security:
#  user:
#    name: admin
#    password: admin
#management:
#  security:
#    roles: SUPERUSER
#  context-path: /scaffold

#swagger:
#  author: oahnus
#  url: www.oahnus.top
#  version: 0.0.1

