
spring:
  application:
    name: scaffold
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scaffold?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  output:
    ansi:
      enabled: always
  aop:
    auto: true
logging:
  pattern:
    console: "%clr(%d %-5level %logger : %msg%n)"
  level:
    top.oahnus: debug
    org.hibernate: ERROR

oahnus:
  config:
    name: 241399
    couponIds:
      - 12
      - 13
      - 14
    coupons: 12, 12, 21