
spring:
  application:
    name: scaffold
  # 主数据源
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scaffold?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initizlSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scaffold2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initizlSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    port: 6379
    host: 127.0.0.1

  jpa:
    database: mysql
    database-platform: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  output:
    ansi:
      enabled: always
  aop:
    auto: true
logging:
  pattern:
    console: "%clr(%d %-5level %logger : %msg%n)"
  level:
    top.oahnus: debug
    org.hibernate: ERROR
  file: app.log
#  path: /var/log
#  如果只配置 logging.file，会在项目的当前路径下生成一个 xxx.log 日志文件。
#  如果只配置 logging.path，在 /var/log文件夹生成一个日志文件为 spring.log
#  若同时使用，则只有logging.file生效