spring:
  application:
    name: scaffold
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scaffold
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      waitMill: 3000
      maxTotal: 500
      maxIdle: 5

logging:
  pattern:
    console: "%clr(%d %-5level %logger : %msg%n)"
  level:
    com.qiyewan: ERROR
    org.hibernate: ERROR