CREATE DATABASE IF NOT EXISTS scaffold2;

-- test table
DROP TABLE IF EXISTS category;
CREATE TABLE category (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)ENGINE = InnoDB AUTO_INCREMENT = 1 CHARSET = utf8 COMMENT 'category';
