spring:
  application:
    name: scaffold-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/scaffold?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  output:
    ansi:
      enabled: always

auth:
  client:
    id: scaffold-auth
    token-header: Z_TOKEN_HEADER
    secret: afj23jn0)8324&#$09sd


server:
  port: 10000

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    # docker 部署开启
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

