spring:
  application:
    name: center

server:
  port: 9999

eureka:
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      # 覆盖Eureka 默认的注册中心地址配置, 若无此项： 会抛出org.apache.http.conn.ConnectTimeoutException: Connect to localhost:8761 timed out
      # EurekaClientConfigBean 类中 设置了默认的注册地址 this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/")
      defaultZone: http://127.0.0.1:9999/eureka/
